# Workflow for building a docker image

name: Build docker image
on:
  push:
    branches:
      - main
      - develop

jobs:
  build_image:
    name: Build a Docker image of the app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile
          push: false